Repository Aeromandy/helpr-back-jfs5, pull requests merged in 2022-12, with the labels that each got.

#19 Entidade e Repositories de FuturoCandidato
  src/main/java/org/soulcodeacademy/helpr/controllers/ChamadoController.java
  src/main/java/org/soulcodeacademy/helpr/domain/FuturoCandidato.java
  src/main/java/org/soulcodeacademy/helpr/domain/enums/Setor.java
  src/main/java/org/soulcodeacademy/helpr/repositories/FuturoCandidatoRepository.java
  src/main/java/org/soulcodeacademy/helpr/services/PopulateService.java
  src/main/resources/application-dev.properties
Labels: enhancement

#25 protecao endpoints funcionario
  src/main/java/org/soulcodeacademy/helpr/controllers/FuncionarioController.java
Labels: enhancement

#28 Controller
  src/main/java/org/soulcodeacademy/helpr/controllers/DependenteController.java
  src/main/java/org/soulcodeacademy/helpr/controllers/FuturoCandidatoController.java
  src/main/java/org/soulcodeacademy/helpr/domain/FuturoCandidato.java
  src/main/java/org/soulcodeacademy/helpr/domain/dto/FuturoCandidatoDTO.java
  src/main/java/org/soulcodeacademy/helpr/domain/enums/Setor.java
  src/main/java/org/soulcodeacademy/helpr/repositories/FuturoCandidatoRepository.java
  src/main/java/org/soulcodeacademy/helpr/services/FuturoCandidatoService.java
  src/main/java/org/soulcodeacademy/helpr/services/PopulateService.java
Labels: bug, enhancement

#30 correcao anotation controllers
  src/main/java/org/soulcodeacademy/helpr/controllers/ChamadoController.java
  src/main/java/org/soulcodeacademy/helpr/controllers/ClienteController.java
  src/main/java/org/soulcodeacademy/helpr/controllers/FuncionarioController.java
Labels: bug, enhancement

#32 Clear code
  src/main/java/org/soulcodeacademy/helpr/config/DevConfig.java
  src/main/java/org/soulcodeacademy/helpr/config/SecurityConfig.java
  src/main/java/org/soulcodeacademy/helpr/controllers/CargoController.java
  src/main/java/org/soulcodeacademy/helpr/controllers/ChamadoController.java
  src/main/java/org/soulcodeacademy/helpr/controllers/ClienteController.java
  src/main/java/org/soulcodeacademy/helpr/controllers/FuncionarioController.java
  src/main/java/org/soulcodeacademy/helpr/controllers/FuturoCandidatoController.java
  src/main/java/org/soulcodeacademy/helpr/controllers/errors/CustomErrorResponse.java
  src/main/java/org/soulcodeacademy/helpr/controllers/errors/ResourceExceptionHandler.java
  src/main/java/org/soulcodeacademy/helpr/domain/Cargo.java
  src/main/java/org/soulcodeacademy/helpr/domain/Cliente.java
  src/main/java/org/soulcodeacademy/helpr/domain/Dependente.java
  src/main/java/org/soulcodeacademy/helpr/domain/Funcionario.java
  src/main/java/org/soulcodeacademy/helpr/domain/FuturoCandidato.java
  src/main/java/org/soulcodeacademy/helpr/domain/Usuario.java
  src/main/java/org/soulcodeacademy/helpr/domain/dto/CargoDTO.java
  src/main/java/org/soulcodeacademy/helpr/domain/dto/ClienteDTO.java
  src/main/java/org/soulcodeacademy/helpr/domain/dto/UsuarioDTO.java
  src/main/java/org/soulcodeacademy/helpr/domain/enums/Perfil.java
  src/main/java/org/soulcodeacademy/helpr/domain/enums/StatusChamado.java
  src/main/java/org/soulcodeacademy/helpr/repositories/CargoRepository.java
  src/main/java/org/soulcodeacademy/helpr/repositories/ChamadoRepository.java
  src/main/java/org/soulcodeacademy/helpr/repositories/ClienteRepository.java
  src/main/java/org/soulcodeacademy/helpr/repositories/FuncionarioRepository.java
  src/main/java/org/soulcodeacademy/helpr/repositories/FuturoCandidatoRepository.java
  src/main/java/org/soulcodeacademy/helpr/repositories/UsuarioRepository.java
  src/main/java/org/soulcodeacademy/helpr/security/TokenFilter.java
  src/main/java/org/soulcodeacademy/helpr/security/TokenUtil.java
  src/main/java/org/soulcodeacademy/helpr/security/UsuarioSecurity.java
  src/main/java/org/soulcodeacademy/helpr/security/UsuarioSecurityService.java
  src/main/java/org/soulcodeacademy/helpr/services/AuthService.java
  src/main/java/org/soulcodeacademy/helpr/services/CargoService.java
  src/main/java/org/soulcodeacademy/helpr/services/ChamadoService.java
  src/main/java/org/soulcodeacademy/helpr/services/ClienteService.java
  src/main/java/org/soulcodeacademy/helpr/services/FuncionarioService.java
  src/main/java/org/soulcodeacademy/helpr/services/PopulateService.java
  src/main/java/org/soulcodeacademy/helpr/services/errors/ParametrosInsuficientesError.java
  src/main/java/org/soulcodeacademy/helpr/services/errors/RecursoNaoEncontradoError.java
Labels: enhancement

#40 Criação de DTO em Dependente
  src/main/java/org/soulcodeacademy/helpr/domain/dto/DependenteDTO.java
Labels: enhancement

#45 Criação do futuro cliente entidade e repository
  src/main/java/org/soulcodeacademy/helpr/domain/FuturoCliente.java
  src/main/java/org/soulcodeacademy/helpr/repositories/FuturoClienteRepository.java
  src/main/java/org/soulcodeacademy/helpr/services/PopulateService.java
Labels: enhancement

#46 Criação de futuro-clienteDTO
  src/main/java/org/soulcodeacademy/helpr/domain/dto/FututoClienteDTO.java
Labels: enhancement

#47 Criação do Futuro Cliente Service
  src/main/java/org/soulcodeacademy/helpr/services/FuturoClienteService.java
Labels: enhancement

#49 sql tasks
  sql/tg_bkp_cargo.sql
  sql/tg_log_chamados.sql
  sql/tg_log_usuarios.sql
Labels: enhancement

#50 Criação do futuro cliente controller
  src/main/java/org/soulcodeacademy/helpr/controllers/FuturoClienteController.java
  src/main/java/org/soulcodeacademy/helpr/services/PopulateService.java
Labels: enhancement

#51 Criação de Controller de Dependente
  src/main/java/org/soulcodeacademy/helpr/controllers/DependenteController.java
  src/main/java/org/soulcodeacademy/helpr/domain/Dependente.java
  src/main/java/org/soulcodeacademy/helpr/repositories/DependenteRepository.java
  src/main/java/org/soulcodeacademy/helpr/services/DependenteService.java
  src/main/java/org/soulcodeacademy/helpr/services/PopulateService.java
Labels: enhancement

#52 correcao populate
  src/main/java/org/soulcodeacademy/helpr/services/PopulateService.java
Labels: bug
